export const data = {
  products: [
    {
      id: 'RX-001',
      name: 'RX.Torax (PA)',
      image: '',
      price: 120,
      countInStock: 10,
      category: '',
      numReviews: 10,
      description: 'Radiografía de Torax',
      codigoProductoSin: 99100,
      unidadMedida: 58,
      especialidad: "Traumatología",
      especialidadDetalle: "Traumatología",
      nroQuirofanoSalaOperaciones: 1,
      especialidadMedico: "Traumatólogo",
      nombreApellidoMedico: "Medicmel",
      nitDocumentoMedico: 392010028,
      nroMatriculaMedico: "string",
      nroFacturaMedico: 1,
    },
    {
      id: 'RX-009',
      name: 'RX. Antebrazo AP-L',
      image: '',
      price: 250,
      countInStock: 10,
      category: '',
      numReviews: 10,
      description: 'Radiografía de antebrazo',
      codigoProductoSin: 99100,
      unidadMedida: 58,
      especialidad: "",
      especialidadDetalle: "string",
      nroQuirofanoSalaOperaciones: 1,
      especialidadMedico: "string",
      nombreApellidoMedico: "Medicmel",
      nitDocumentoMedico: 392010028,
      nroMatriculaMedico: "string",
      nroFacturaMedico: 1,
    },
    {
      id: 'RX-007',
      name: 'RX.RAYOS X PORTATIL EN PISO',
      image: '',
      price: 150,
      countInStock: 15,
      category: '',
      numReviews: 14,
      description: 'Rayos x portatil de piso',
      codigoProductoSin: 99100,
      unidadMedida: 58,
      especialidad: "",
      especialidadDetalle: "string",
      nroQuirofanoSalaOperaciones: 1,
      especialidadMedico: "string",
      nombreApellidoMedico: "Medicmel",
      nitDocumentoMedico: 392010028,
      nroMatriculaMedico: "string",
      nroFacturaMedico: 1,
    },
    {
      id: '4',
      name: 'Medicina 4',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category2',
      numReviews: 10,
      description: 'high quality product',
      codigoProductoSin: 99100,
      descripcion: "ñÑáÁ",
      unidadMedida: 58,
      especialidad: "Traumatología",
      especialidadDetalle: "string",
      nroQuirofanoSalaOperaciones: 1,
      especialidadMedico: "string",
      nombreApellidoMedico: "Medicmel",
      nitDocumentoMedico: 392010028,
      nroMatriculaMedico: "string",
      nroFacturaMedico: 1,
    },
    {
      id: '5',
      name: 'Medicina 5',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category3',
      numReviews: 10,
      description: 'high quality product',
      codigoProductoSin: 99100,
      descripcion: "ñÑáÁ",
      unidadMedida: 58,
      especialidad: "Traumatología",
      especialidadDetalle: "string",
      nroQuirofanoSalaOperaciones: 1,
      especialidadMedico: "string",
      nombreApellidoMedico: "Medicmel",
      nitDocumentoMedico: 392010028,
      nroMatriculaMedico: "string",
      nroFacturaMedico: 1,
    },
    {
      id: '6',
      name: 'Medicina 6',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category4',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '7',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '8',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '9',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '10',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '11',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '12',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '13',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '14',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '15',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '16',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '17',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '18',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '19',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '20',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '21',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '22',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '23',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '24',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
  ],
}
